# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_exit.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class  Ui_Form_user_exit(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(434, 712)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 461, 721))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("image/фон регистрации.png"))
        self.label.setObjectName("label")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_2.setGeometry(QtCore.QRect(-70, 30, 581, 51))
        self.textBrowser_2.setStyleSheet("Войдите или зарегистрируйтесь!")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_3.setObjectName("label_3")
        self.line_edit_fio = QtWidgets.QLineEdit(Form)
        self.line_edit_fio.setGeometry(QtCore.QRect(10, 170, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_edit_fio.setFont(font)
        self.line_edit_fio.setObjectName("line_edit_fio")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(10, 220, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_9.setObjectName("label_9")
        self.date_edit_bdate = QtWidgets.QDateEdit(Form)
        self.date_edit_bdate.setGeometry(QtCore.QRect(10, 270, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.date_edit_bdate.setFont(font)
        self.date_edit_bdate.setObjectName("date_edit_bdate")
        self.push_button_exit = QtWidgets.QPushButton(Form)
        self.push_button_exit.setGeometry(QtCore.QRect(100, 330, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.push_button_exit.setFont(font)
        self.push_button_exit.setObjectName("push_button_exit")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(160, 460, 55, 16))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(0, 440, 441, 111))
        self.textBrowser.setObjectName("textBrowser")
        self.push_button_registration_reg_3 = QtWidgets.QPushButton(Form)
        self.push_button_registration_reg_3.setGeometry(QtCore.QRect(100, 580, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.push_button_registration_reg_3.setFont(font)
        self.push_button_registration_reg_3.setObjectName("push_button_registration_reg_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.textBrowser_2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">Вход/регистрация пациента</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "Введите ФИО:"))
        self.label_9.setText(_translate("Form", "Введите дату рождения:"))
        self.push_button_exit.setText(_translate("Form", "Войти"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Если вы не являетесь пациентом нашей клиники, можете зарегистрироваться самостоятельно или обратиться в нашу регистратуру по номеру 221-87-23</span></p></body></html>"))
        self.push_button_registration_reg_3.setText(_translate("Form", "Регистрация"))
